package:
  name: collating
  version: '1.0.1'

source:
  #path: /Users/clarabird/github/collating/collating/__main__.py
  git_url: https://github.com/cbirdferrer/collating/

build:
  noarch: python
  number: '0'
  script: python setup.py install #python -m pip install #--no-deps --ignore-installed  #

requirements:
  build:
    - python #setup.py install
 #   - setuptools
  run:
    - python
    - numpy
    - pandas
    - pyqt
    - setuptools

# tests:
#    imports:
#     - morphometrix

about:
  home: https://github.com/cbirdferrer/collating
  license: MIT
  summary: A GUI to collate output of MorphoMetriX
