package:
  name: collatrix
  version: '1.0.5'

source:
  #path: /Users/clarabird/github/collating/collatrix/__main__.py
  git_url: https://github.com/cbirdferrer/collatrix/

build:
  noarch: python
  number: '0'
  script: python setup.py install #python -m pip install #--no-deps --ignore-installed  #

requirements:
  build:
    - python #setup.py install
 #   - setuptools
  run:
    - python
    - numpy
    - pandas
    - pyqt=5
    - setuptools
    - scipy

about:
  home: https://github.com/cbirdferrer/collatrix
  license: MIT
  summary: A GUI to collate output of MorphoMetriX
