package:
  name: collatrix
  version: '1.0.8'

source:
  git_url: https://github.com/cbirdferrer/collatrix/

build:
  noarch: python
  number: '0'
  script:
    - mkdir -p ${SP_DIR}
    - cp -r src/* ${SP_DIR}
  entry_points:
    - collatrix = collatrix.__main__:main

requirements:
  build:
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas
    - pyqt=5
    - setuptools
    - scipy

about:
  home: https://github.com/cbirdferrer/collatrix
  license: MIT
  summary: A GUI to collate output of MorphoMetriX
