{% set name = "sep" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a35704cffadbd042f931899a5564c539835fa7049d0cafff407d7ec7727d3aaa

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy x.x
    - pip
    - python
  run:
    - numpy x.x
    - python

test:
  imports:
    - sep

about:
  home: "https://github.com/kbarbary/sep"
  license: "GNU Lesser General Public v3 or later (LGPLv3+)"
  license_family: LGPL
  license_file:
  summary: "Astronomical source extraction and photometry library"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
